// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: api/proto/game.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息ID枚举
type MsgID int32

const (
	MsgID_UNKNOWN MsgID = 0
	// Client to Server
	MsgID_C2S_JOIN_ROOM_REQ    MsgID = 101
	MsgID_C2S_PLAYER_READY_REQ MsgID = 102
	MsgID_C2S_BID_BANKER_REQ   MsgID = 103
	MsgID_C2S_PLACE_BET_REQ    MsgID = 104
	MsgID_C2S_SHOWDOWN_REQ     MsgID = 105
	MsgID_C2S_LEAVE_ROOM_REQ   MsgID = 106
	// Server to Client
	MsgID_S2C_JOIN_ROOM_ACK       MsgID = 201
	MsgID_S2C_BID_BANKER_ACK      MsgID = 210 // 新增
	MsgID_S2C_PLACE_BET_ACK       MsgID = 211 // 新增
	MsgID_S2C_SHOWDOWN_ACK        MsgID = 212 // 新增
	MsgID_S2C_SYNC_ROOM_STATE_NTF MsgID = 202
	MsgID_S2C_GAME_START_NTF      MsgID = 203
	MsgID_S2C_DEAL_CARDS_NTF      MsgID = 204
	MsgID_S2C_BID_BANKER_NTF      MsgID = 205
	MsgID_S2C_BET_NTF             MsgID = 206
	MsgID_S2C_SHOWDOWN_NTF        MsgID = 207
	MsgID_S2C_GAME_RESULT_NTF     MsgID = 208
	MsgID_S2C_PLAYER_LEAVE_NTF    MsgID = 209
)

// Enum value maps for MsgID.
var (
	MsgID_name = map[int32]string{
		0:   "UNKNOWN",
		101: "C2S_JOIN_ROOM_REQ",
		102: "C2S_PLAYER_READY_REQ",
		103: "C2S_BID_BANKER_REQ",
		104: "C2S_PLACE_BET_REQ",
		105: "C2S_SHOWDOWN_REQ",
		106: "C2S_LEAVE_ROOM_REQ",
		201: "S2C_JOIN_ROOM_ACK",
		210: "S2C_BID_BANKER_ACK",
		211: "S2C_PLACE_BET_ACK",
		212: "S2C_SHOWDOWN_ACK",
		202: "S2C_SYNC_ROOM_STATE_NTF",
		203: "S2C_GAME_START_NTF",
		204: "S2C_DEAL_CARDS_NTF",
		205: "S2C_BID_BANKER_NTF",
		206: "S2C_BET_NTF",
		207: "S2C_SHOWDOWN_NTF",
		208: "S2C_GAME_RESULT_NTF",
		209: "S2C_PLAYER_LEAVE_NTF",
	}
	MsgID_value = map[string]int32{
		"UNKNOWN":                 0,
		"C2S_JOIN_ROOM_REQ":       101,
		"C2S_PLAYER_READY_REQ":    102,
		"C2S_BID_BANKER_REQ":      103,
		"C2S_PLACE_BET_REQ":       104,
		"C2S_SHOWDOWN_REQ":        105,
		"C2S_LEAVE_ROOM_REQ":      106,
		"S2C_JOIN_ROOM_ACK":       201,
		"S2C_BID_BANKER_ACK":      210,
		"S2C_PLACE_BET_ACK":       211,
		"S2C_SHOWDOWN_ACK":        212,
		"S2C_SYNC_ROOM_STATE_NTF": 202,
		"S2C_GAME_START_NTF":      203,
		"S2C_DEAL_CARDS_NTF":      204,
		"S2C_BID_BANKER_NTF":      205,
		"S2C_BET_NTF":             206,
		"S2C_SHOWDOWN_NTF":        207,
		"S2C_GAME_RESULT_NTF":     208,
		"S2C_PLAYER_LEAVE_NTF":    209,
	}
)

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_proto_enumTypes[0].Descriptor()
}

func (MsgID) Type() protoreflect.EnumType {
	return &file_api_proto_game_proto_enumTypes[0]
}

func (x MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgID.Descriptor instead.
func (MsgID) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{0}
}

// 卡牌花色
type Suit int32

const (
	Suit_SUIT_UNKNOWN Suit = 0
	Suit_SPADES       Suit = 1 // 黑桃
	Suit_HEARTS       Suit = 2 // 红心
	Suit_CLUBS        Suit = 3 // 梅花
	Suit_DIAMONDS     Suit = 4 // 方块
)

// Enum value maps for Suit.
var (
	Suit_name = map[int32]string{
		0: "SUIT_UNKNOWN",
		1: "SPADES",
		2: "HEARTS",
		3: "CLUBS",
		4: "DIAMONDS",
	}
	Suit_value = map[string]int32{
		"SUIT_UNKNOWN": 0,
		"SPADES":       1,
		"HEARTS":       2,
		"CLUBS":        3,
		"DIAMONDS":     4,
	}
)

func (x Suit) Enum() *Suit {
	p := new(Suit)
	*p = x
	return p
}

func (x Suit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Suit) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_proto_enumTypes[1].Descriptor()
}

func (Suit) Type() protoreflect.EnumType {
	return &file_api_proto_game_proto_enumTypes[1]
}

func (x Suit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Suit.Descriptor instead.
func (Suit) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{1}
}

// 卡牌点数
type Rank int32

const (
	Rank_RANK_UNKNOWN Rank = 0
	Rank_ACE          Rank = 1
	Rank_TWO          Rank = 2
	Rank_THREE        Rank = 3
	Rank_FOUR         Rank = 4
	Rank_FIVE         Rank = 5
	Rank_SIX          Rank = 6
	Rank_SEVEN        Rank = 7
	Rank_EIGHT        Rank = 8
	Rank_NINE         Rank = 9
	Rank_TEN          Rank = 10
	Rank_JACK         Rank = 11
	Rank_QUEEN        Rank = 12
	Rank_KING         Rank = 13
)

// Enum value maps for Rank.
var (
	Rank_name = map[int32]string{
		0:  "RANK_UNKNOWN",
		1:  "ACE",
		2:  "TWO",
		3:  "THREE",
		4:  "FOUR",
		5:  "FIVE",
		6:  "SIX",
		7:  "SEVEN",
		8:  "EIGHT",
		9:  "NINE",
		10: "TEN",
		11: "JACK",
		12: "QUEEN",
		13: "KING",
	}
	Rank_value = map[string]int32{
		"RANK_UNKNOWN": 0,
		"ACE":          1,
		"TWO":          2,
		"THREE":        3,
		"FOUR":         4,
		"FIVE":         5,
		"SIX":          6,
		"SEVEN":        7,
		"EIGHT":        8,
		"NINE":         9,
		"TEN":          10,
		"JACK":         11,
		"QUEEN":        12,
		"KING":         13,
	}
)

func (x Rank) Enum() *Rank {
	p := new(Rank)
	*p = x
	return p
}

func (x Rank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rank) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_proto_enumTypes[2].Descriptor()
}

func (Rank) Type() protoreflect.EnumType {
	return &file_api_proto_game_proto_enumTypes[2]
}

func (x Rank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rank.Descriptor instead.
func (Rank) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{2}
}

// 牌型
type CardPattern int32

const (
	CardPattern_PATTERN_UNKNOWN CardPattern = 0
	CardPattern_NO_NIU          CardPattern = 1
	CardPattern_NIU_1           CardPattern = 2
	CardPattern_NIU_2           CardPattern = 3
	CardPattern_NIU_3           CardPattern = 4
	CardPattern_NIU_4           CardPattern = 5
	CardPattern_NIU_5           CardPattern = 6
	CardPattern_NIU_6           CardPattern = 7
	CardPattern_NIU_7           CardPattern = 8
	CardPattern_NIU_8           CardPattern = 9
	CardPattern_NIU_9           CardPattern = 10
	CardPattern_NIU_NIU         CardPattern = 11
	CardPattern_FIVE_FLOWER_NIU CardPattern = 12 // 五花牛
	CardPattern_BOMB_NIU        CardPattern = 13 // 炸弹牛
	CardPattern_FIVE_SMALL_NIU  CardPattern = 14 // 五小牛
)

// Enum value maps for CardPattern.
var (
	CardPattern_name = map[int32]string{
		0:  "PATTERN_UNKNOWN",
		1:  "NO_NIU",
		2:  "NIU_1",
		3:  "NIU_2",
		4:  "NIU_3",
		5:  "NIU_4",
		6:  "NIU_5",
		7:  "NIU_6",
		8:  "NIU_7",
		9:  "NIU_8",
		10: "NIU_9",
		11: "NIU_NIU",
		12: "FIVE_FLOWER_NIU",
		13: "BOMB_NIU",
		14: "FIVE_SMALL_NIU",
	}
	CardPattern_value = map[string]int32{
		"PATTERN_UNKNOWN": 0,
		"NO_NIU":          1,
		"NIU_1":           2,
		"NIU_2":           3,
		"NIU_3":           4,
		"NIU_4":           5,
		"NIU_5":           6,
		"NIU_6":           7,
		"NIU_7":           8,
		"NIU_8":           9,
		"NIU_9":           10,
		"NIU_NIU":         11,
		"FIVE_FLOWER_NIU": 12,
		"BOMB_NIU":        13,
		"FIVE_SMALL_NIU":  14,
	}
)

func (x CardPattern) Enum() *CardPattern {
	p := new(CardPattern)
	*p = x
	return p
}

func (x CardPattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardPattern) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_proto_enumTypes[3].Descriptor()
}

func (CardPattern) Type() protoreflect.EnumType {
	return &file_api_proto_game_proto_enumTypes[3]
}

func (x CardPattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardPattern.Descriptor instead.
func (CardPattern) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{3}
}

// 玩家状态
type PlayerStatus int32

const (
	PlayerStatus_STATUS_UNKNOWN PlayerStatus = 0
	PlayerStatus_WAITING        PlayerStatus = 1
	PlayerStatus_READY          PlayerStatus = 2
	PlayerStatus_PLAYING        PlayerStatus = 3
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "WAITING",
		2: "READY",
		3: "PLAYING",
	}
	PlayerStatus_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"WAITING":        1,
		"READY":          2,
		"PLAYING":        3,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_proto_enumTypes[4].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_api_proto_game_proto_enumTypes[4]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{4}
}

// 游戏阶段
type GameState int32

const (
	GameState_STATE_UNKNOWN       GameState = 0
	GameState_WAITING_FOR_PLAYERS GameState = 1
	GameState_DEALING             GameState = 2
	GameState_BIDDING             GameState = 3
	GameState_BETTING             GameState = 4
	GameState_SHOWDOWN            GameState = 5
	GameState_SETTLEMENT          GameState = 6
)

// Enum value maps for GameState.
var (
	GameState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "WAITING_FOR_PLAYERS",
		2: "DEALING",
		3: "BIDDING",
		4: "BETTING",
		5: "SHOWDOWN",
		6: "SETTLEMENT",
	}
	GameState_value = map[string]int32{
		"STATE_UNKNOWN":       0,
		"WAITING_FOR_PLAYERS": 1,
		"DEALING":             2,
		"BIDDING":             3,
		"BETTING":             4,
		"SHOWDOWN":            5,
		"SETTLEMENT":          6,
	}
)

func (x GameState) Enum() *GameState {
	p := new(GameState)
	*p = x
	return p
}

func (x GameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_game_proto_enumTypes[5].Descriptor()
}

func (GameState) Type() protoreflect.EnumType {
	return &file_api_proto_game_proto_enumTypes[5]
}

func (x GameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState.Descriptor instead.
func (GameState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{5}
}

// 数据结构
type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suit          Suit                   `protobuf:"varint,1,opt,name=suit,proto3,enum=game.Suit" json:"suit,omitempty"`
	Rank          Rank                   `protobuf:"varint,2,opt,name=rank,proto3,enum=game.Rank" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_api_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetSuit() Suit {
	if x != nil {
		return x.Suit
	}
	return Suit_SUIT_UNKNOWN
}

func (x *Card) GetRank() Rank {
	if x != nil {
		return x.Rank
	}
	return Rank_RANK_UNKNOWN
}

type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Score         int64                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Status        PlayerStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=game.PlayerStatus" json:"status,omitempty"`
	IsBanker      bool                   `protobuf:"varint,5,opt,name=is_banker,json=isBanker,proto3" json:"is_banker,omitempty"`
	Hand          []*Card                `protobuf:"bytes,6,rep,name=hand,proto3" json:"hand,omitempty"`
	CardPattern   CardPattern            `protobuf:"varint,7,opt,name=card_pattern,json=cardPattern,proto3,enum=game.CardPattern" json:"card_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_api_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfo) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerInfo) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerInfo) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_STATUS_UNKNOWN
}

func (x *PlayerInfo) GetIsBanker() bool {
	if x != nil {
		return x.IsBanker
	}
	return false
}

func (x *PlayerInfo) GetHand() []*Card {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *PlayerInfo) GetCardPattern() CardPattern {
	if x != nil {
		return x.CardPattern
	}
	return CardPattern_PATTERN_UNKNOWN
}

// C2S 消息
type C2S_JoinRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_JoinRoomReq) Reset() {
	*x = C2S_JoinRoomReq{}
	mi := &file_api_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_JoinRoomReq) ProtoMessage() {}

func (x *C2S_JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_JoinRoomReq.ProtoReflect.Descriptor instead.
func (*C2S_JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_JoinRoomReq) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type C2S_PlayerReadyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReady       bool                   `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_PlayerReadyReq) Reset() {
	*x = C2S_PlayerReadyReq{}
	mi := &file_api_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_PlayerReadyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_PlayerReadyReq) ProtoMessage() {}

func (x *C2S_PlayerReadyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_PlayerReadyReq.ProtoReflect.Descriptor instead.
func (*C2S_PlayerReadyReq) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_PlayerReadyReq) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type C2S_BidBankerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Multiple      int32                  `protobuf:"varint,1,opt,name=multiple,proto3" json:"multiple,omitempty"` // 抢庄倍数, 0表示不抢
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_BidBankerReq) Reset() {
	*x = C2S_BidBankerReq{}
	mi := &file_api_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_BidBankerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_BidBankerReq) ProtoMessage() {}

func (x *C2S_BidBankerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_BidBankerReq.ProtoReflect.Descriptor instead.
func (*C2S_BidBankerReq) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *C2S_BidBankerReq) GetMultiple() int32 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

type C2S_PlaceBetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Multiple      int32                  `protobuf:"varint,1,opt,name=multiple,proto3" json:"multiple,omitempty"` // 下注倍数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_PlaceBetReq) Reset() {
	*x = C2S_PlaceBetReq{}
	mi := &file_api_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_PlaceBetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_PlaceBetReq) ProtoMessage() {}

func (x *C2S_PlaceBetReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_PlaceBetReq.ProtoReflect.Descriptor instead.
func (*C2S_PlaceBetReq) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_PlaceBetReq) GetMultiple() int32 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

type C2S_ShowdownReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端计算好牌型后，将手牌顺序调整好再发给服务器
	SortedHand    []*Card `protobuf:"bytes,1,rep,name=sorted_hand,json=sortedHand,proto3" json:"sorted_hand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_ShowdownReq) Reset() {
	*x = C2S_ShowdownReq{}
	mi := &file_api_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_ShowdownReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_ShowdownReq) ProtoMessage() {}

func (x *C2S_ShowdownReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_ShowdownReq.ProtoReflect.Descriptor instead.
func (*C2S_ShowdownReq) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_ShowdownReq) GetSortedHand() []*Card {
	if x != nil {
		return x.SortedHand
	}
	return nil
}

type C2S_LeaveRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_LeaveRoomReq) Reset() {
	*x = C2S_LeaveRoomReq{}
	mi := &file_api_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_LeaveRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_LeaveRoomReq) ProtoMessage() {}

func (x *C2S_LeaveRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_LeaveRoomReq.ProtoReflect.Descriptor instead.
func (*C2S_LeaveRoomReq) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{7}
}

// S2C 消息
type S2C_JoinRoomAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       int32                  `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"` // 0 for success
	RoomInfo      *RoomInfo              `protobuf:"bytes,2,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_JoinRoomAck) Reset() {
	*x = S2C_JoinRoomAck{}
	mi := &file_api_proto_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_JoinRoomAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_JoinRoomAck) ProtoMessage() {}

func (x *S2C_JoinRoomAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_JoinRoomAck.ProtoReflect.Descriptor instead.
func (*S2C_JoinRoomAck) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{8}
}

func (x *S2C_JoinRoomAck) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *S2C_JoinRoomAck) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

// 新增: S2C_BidBankerAck 响应客户端的抢庄请求
type S2C_BidBankerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       int32                  `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`    // 0 for success
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 成功抢到庄的玩家ID，如果ret_code非0则此字段无意义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_BidBankerAck) Reset() {
	*x = S2C_BidBankerAck{}
	mi := &file_api_proto_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_BidBankerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_BidBankerAck) ProtoMessage() {}

func (x *S2C_BidBankerAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_BidBankerAck.ProtoReflect.Descriptor instead.
func (*S2C_BidBankerAck) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{9}
}

func (x *S2C_BidBankerAck) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *S2C_BidBankerAck) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 新增: S2C_PlaceBetAck 响应客户端的下注请求
type S2C_PlaceBetAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       int32                  `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"` // 0 for success
	Multiple      int32                  `protobuf:"varint,2,opt,name=multiple,proto3" json:"multiple,omitempty"`              // 成功下注的倍数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_PlaceBetAck) Reset() {
	*x = S2C_PlaceBetAck{}
	mi := &file_api_proto_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_PlaceBetAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_PlaceBetAck) ProtoMessage() {}

func (x *S2C_PlaceBetAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_PlaceBetAck.ProtoReflect.Descriptor instead.
func (*S2C_PlaceBetAck) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{10}
}

func (x *S2C_PlaceBetAck) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *S2C_PlaceBetAck) GetMultiple() int32 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

// 新增: S2C_ShowdownAck 响应客户端的摊牌请求
type S2C_ShowdownAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetCode       int32                  `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"` // 0 for success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ShowdownAck) Reset() {
	*x = S2C_ShowdownAck{}
	mi := &file_api_proto_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ShowdownAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ShowdownAck) ProtoMessage() {}

func (x *S2C_ShowdownAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ShowdownAck.ProtoReflect.Descriptor instead.
func (*S2C_ShowdownAck) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{11}
}

func (x *S2C_ShowdownAck) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Players       []*PlayerInfo          `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	GameState     GameState              `protobuf:"varint,3,opt,name=game_state,json=gameState,proto3,enum=game.GameState" json:"game_state,omitempty"`
	BankerId      int64                  `protobuf:"varint,4,opt,name=banker_id,json=bankerId,proto3" json:"banker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_api_proto_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{12}
}

func (x *RoomInfo) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RoomInfo) GetGameState() GameState {
	if x != nil {
		return x.GameState
	}
	return GameState_STATE_UNKNOWN
}

func (x *RoomInfo) GetBankerId() int64 {
	if x != nil {
		return x.BankerId
	}
	return 0
}

type S2C_SyncRoomStateNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomInfo      *RoomInfo              `protobuf:"bytes,1,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_SyncRoomStateNtf) Reset() {
	*x = S2C_SyncRoomStateNtf{}
	mi := &file_api_proto_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_SyncRoomStateNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_SyncRoomStateNtf) ProtoMessage() {}

func (x *S2C_SyncRoomStateNtf) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_SyncRoomStateNtf.ProtoReflect.Descriptor instead.
func (*S2C_SyncRoomStateNtf) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{13}
}

func (x *S2C_SyncRoomStateNtf) GetRoomInfo() *RoomInfo {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

type S2C_GameStartNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankerId      int64                  `protobuf:"varint,1,opt,name=banker_id,json=bankerId,proto3" json:"banker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_GameStartNtf) Reset() {
	*x = S2C_GameStartNtf{}
	mi := &file_api_proto_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_GameStartNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GameStartNtf) ProtoMessage() {}

func (x *S2C_GameStartNtf) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GameStartNtf.ProtoReflect.Descriptor instead.
func (*S2C_GameStartNtf) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{14}
}

func (x *S2C_GameStartNtf) GetBankerId() int64 {
	if x != nil {
		return x.BankerId
	}
	return 0
}

type S2C_DealCardsNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hand          []*Card                `protobuf:"bytes,1,rep,name=hand,proto3" json:"hand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_DealCardsNtf) Reset() {
	*x = S2C_DealCardsNtf{}
	mi := &file_api_proto_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_DealCardsNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_DealCardsNtf) ProtoMessage() {}

func (x *S2C_DealCardsNtf) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_DealCardsNtf.ProtoReflect.Descriptor instead.
func (*S2C_DealCardsNtf) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{15}
}

func (x *S2C_DealCardsNtf) GetHand() []*Card {
	if x != nil {
		return x.Hand
	}
	return nil
}

type S2C_BidBankerNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countdown     int32                  `protobuf:"varint,1,opt,name=countdown,proto3" json:"countdown,omitempty"` // 倒计时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_BidBankerNtf) Reset() {
	*x = S2C_BidBankerNtf{}
	mi := &file_api_proto_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_BidBankerNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_BidBankerNtf) ProtoMessage() {}

func (x *S2C_BidBankerNtf) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_BidBankerNtf.ProtoReflect.Descriptor instead.
func (*S2C_BidBankerNtf) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{16}
}

func (x *S2C_BidBankerNtf) GetCountdown() int32 {
	if x != nil {
		return x.Countdown
	}
	return 0
}

type S2C_BetNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankerId      int64                  `protobuf:"varint,1,opt,name=banker_id,json=bankerId,proto3" json:"banker_id,omitempty"`
	Countdown     int32                  `protobuf:"varint,2,opt,name=countdown,proto3" json:"countdown,omitempty"` // 倒计时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_BetNtf) Reset() {
	*x = S2C_BetNtf{}
	mi := &file_api_proto_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_BetNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_BetNtf) ProtoMessage() {}

func (x *S2C_BetNtf) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_BetNtf.ProtoReflect.Descriptor instead.
func (*S2C_BetNtf) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{17}
}

func (x *S2C_BetNtf) GetBankerId() int64 {
	if x != nil {
		return x.BankerId
	}
	return 0
}

func (x *S2C_BetNtf) GetCountdown() int32 {
	if x != nil {
		return x.Countdown
	}
	return 0
}

type S2C_ShowdownNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countdown     int32                  `protobuf:"varint,1,opt,name=countdown,proto3" json:"countdown,omitempty"` // 倒计时
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ShowdownNtf) Reset() {
	*x = S2C_ShowdownNtf{}
	mi := &file_api_proto_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ShowdownNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ShowdownNtf) ProtoMessage() {}

func (x *S2C_ShowdownNtf) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ShowdownNtf.ProtoReflect.Descriptor instead.
func (*S2C_ShowdownNtf) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{18}
}

func (x *S2C_ShowdownNtf) GetCountdown() int32 {
	if x != nil {
		return x.Countdown
	}
	return 0
}

type PlayerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Hand          []*Card                `protobuf:"bytes,2,rep,name=hand,proto3" json:"hand,omitempty"`
	CardPattern   CardPattern            `protobuf:"varint,3,opt,name=card_pattern,json=cardPattern,proto3,enum=game.CardPattern" json:"card_pattern,omitempty"`
	ScoreChange   int64                  `protobuf:"varint,4,opt,name=score_change,json=scoreChange,proto3" json:"score_change,omitempty"`
	FinalScore    int64                  `protobuf:"varint,5,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResult) Reset() {
	*x = PlayerResult{}
	mi := &file_api_proto_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResult) ProtoMessage() {}

func (x *PlayerResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResult.ProtoReflect.Descriptor instead.
func (*PlayerResult) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{19}
}

func (x *PlayerResult) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerResult) GetHand() []*Card {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *PlayerResult) GetCardPattern() CardPattern {
	if x != nil {
		return x.CardPattern
	}
	return CardPattern_PATTERN_UNKNOWN
}

func (x *PlayerResult) GetScoreChange() int64 {
	if x != nil {
		return x.ScoreChange
	}
	return 0
}

func (x *PlayerResult) GetFinalScore() int64 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

type S2C_GameResultNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PlayerResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_GameResultNtf) Reset() {
	*x = S2C_GameResultNtf{}
	mi := &file_api_proto_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_GameResultNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_GameResultNtf) ProtoMessage() {}

func (x *S2C_GameResultNtf) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_GameResultNtf.ProtoReflect.Descriptor instead.
func (*S2C_GameResultNtf) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{20}
}

func (x *S2C_GameResultNtf) GetResults() []*PlayerResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type S2C_PlayerLeaveNtf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_PlayerLeaveNtf) Reset() {
	*x = S2C_PlayerLeaveNtf{}
	mi := &file_api_proto_game_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_PlayerLeaveNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_PlayerLeaveNtf) ProtoMessage() {}

func (x *S2C_PlayerLeaveNtf) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_game_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_PlayerLeaveNtf.ProtoReflect.Descriptor instead.
func (*S2C_PlayerLeaveNtf) Descriptor() ([]byte, []int) {
	return file_api_proto_game_proto_rawDescGZIP(), []int{21}
}

func (x *S2C_PlayerLeaveNtf) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_api_proto_game_proto protoreflect.FileDescriptor

const file_api_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/game.proto\x12\x04game\"F\n" +
	"\x04Card\x12\x1e\n" +
	"\x04suit\x18\x01 \x01(\x0e2\n" +
	".game.SuitR\x04suit\x12\x1e\n" +
	"\x04rank\x18\x02 \x01(\x0e2\n" +
	".game.RankR\x04rank\"\xfa\x01\n" +
	"\n" +
	"PlayerInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.game.PlayerStatusR\x06status\x12\x1b\n" +
	"\tis_banker\x18\x05 \x01(\bR\bisBanker\x12\x1e\n" +
	"\x04hand\x18\x06 \x03(\v2\n" +
	".game.CardR\x04hand\x124\n" +
	"\fcard_pattern\x18\a \x01(\x0e2\x11.game.CardPatternR\vcardPattern\"*\n" +
	"\x0fC2S_JoinRoomReq\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\"/\n" +
	"\x12C2S_PlayerReadyReq\x12\x19\n" +
	"\bis_ready\x18\x01 \x01(\bR\aisReady\".\n" +
	"\x10C2S_BidBankerReq\x12\x1a\n" +
	"\bmultiple\x18\x01 \x01(\x05R\bmultiple\"-\n" +
	"\x0fC2S_PlaceBetReq\x12\x1a\n" +
	"\bmultiple\x18\x01 \x01(\x05R\bmultiple\">\n" +
	"\x0fC2S_ShowdownReq\x12+\n" +
	"\vsorted_hand\x18\x01 \x03(\v2\n" +
	".game.CardR\n" +
	"sortedHand\"\x12\n" +
	"\x10C2S_LeaveRoomReq\"Y\n" +
	"\x0fS2C_JoinRoomAck\x12\x19\n" +
	"\bret_code\x18\x01 \x01(\x05R\aretCode\x12+\n" +
	"\troom_info\x18\x02 \x01(\v2\x0e.game.RoomInfoR\broomInfo\"J\n" +
	"\x10S2C_BidBankerAck\x12\x19\n" +
	"\bret_code\x18\x01 \x01(\x05R\aretCode\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\"H\n" +
	"\x0fS2C_PlaceBetAck\x12\x19\n" +
	"\bret_code\x18\x01 \x01(\x05R\aretCode\x12\x1a\n" +
	"\bmultiple\x18\x02 \x01(\x05R\bmultiple\",\n" +
	"\x0fS2C_ShowdownAck\x12\x19\n" +
	"\bret_code\x18\x01 \x01(\x05R\aretCode\"\x9c\x01\n" +
	"\bRoomInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12*\n" +
	"\aplayers\x18\x02 \x03(\v2\x10.game.PlayerInfoR\aplayers\x12.\n" +
	"\n" +
	"game_state\x18\x03 \x01(\x0e2\x0f.game.GameStateR\tgameState\x12\x1b\n" +
	"\tbanker_id\x18\x04 \x01(\x03R\bbankerId\"C\n" +
	"\x14S2C_SyncRoomStateNtf\x12+\n" +
	"\troom_info\x18\x01 \x01(\v2\x0e.game.RoomInfoR\broomInfo\"/\n" +
	"\x10S2C_GameStartNtf\x12\x1b\n" +
	"\tbanker_id\x18\x01 \x01(\x03R\bbankerId\"2\n" +
	"\x10S2C_DealCardsNtf\x12\x1e\n" +
	"\x04hand\x18\x01 \x03(\v2\n" +
	".game.CardR\x04hand\"0\n" +
	"\x10S2C_BidBankerNtf\x12\x1c\n" +
	"\tcountdown\x18\x01 \x01(\x05R\tcountdown\"G\n" +
	"\n" +
	"S2C_BetNtf\x12\x1b\n" +
	"\tbanker_id\x18\x01 \x01(\x03R\bbankerId\x12\x1c\n" +
	"\tcountdown\x18\x02 \x01(\x05R\tcountdown\"/\n" +
	"\x0fS2C_ShowdownNtf\x12\x1c\n" +
	"\tcountdown\x18\x01 \x01(\x05R\tcountdown\"\xc5\x01\n" +
	"\fPlayerResult\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1e\n" +
	"\x04hand\x18\x02 \x03(\v2\n" +
	".game.CardR\x04hand\x124\n" +
	"\fcard_pattern\x18\x03 \x01(\x0e2\x11.game.CardPatternR\vcardPattern\x12!\n" +
	"\fscore_change\x18\x04 \x01(\x03R\vscoreChange\x12\x1f\n" +
	"\vfinal_score\x18\x05 \x01(\x03R\n" +
	"finalScore\"A\n" +
	"\x11S2C_GameResultNtf\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.game.PlayerResultR\aresults\"1\n" +
	"\x12S2C_PlayerLeaveNtf\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId*\xc9\x03\n" +
	"\x05MsgID\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x15\n" +
	"\x11C2S_JOIN_ROOM_REQ\x10e\x12\x18\n" +
	"\x14C2S_PLAYER_READY_REQ\x10f\x12\x16\n" +
	"\x12C2S_BID_BANKER_REQ\x10g\x12\x15\n" +
	"\x11C2S_PLACE_BET_REQ\x10h\x12\x14\n" +
	"\x10C2S_SHOWDOWN_REQ\x10i\x12\x16\n" +
	"\x12C2S_LEAVE_ROOM_REQ\x10j\x12\x16\n" +
	"\x11S2C_JOIN_ROOM_ACK\x10\xc9\x01\x12\x17\n" +
	"\x12S2C_BID_BANKER_ACK\x10\xd2\x01\x12\x16\n" +
	"\x11S2C_PLACE_BET_ACK\x10\xd3\x01\x12\x15\n" +
	"\x10S2C_SHOWDOWN_ACK\x10\xd4\x01\x12\x1c\n" +
	"\x17S2C_SYNC_ROOM_STATE_NTF\x10\xca\x01\x12\x17\n" +
	"\x12S2C_GAME_START_NTF\x10\xcb\x01\x12\x17\n" +
	"\x12S2C_DEAL_CARDS_NTF\x10\xcc\x01\x12\x17\n" +
	"\x12S2C_BID_BANKER_NTF\x10\xcd\x01\x12\x10\n" +
	"\vS2C_BET_NTF\x10\xce\x01\x12\x15\n" +
	"\x10S2C_SHOWDOWN_NTF\x10\xcf\x01\x12\x18\n" +
	"\x13S2C_GAME_RESULT_NTF\x10\xd0\x01\x12\x19\n" +
	"\x14S2C_PLAYER_LEAVE_NTF\x10\xd1\x01*I\n" +
	"\x04Suit\x12\x10\n" +
	"\fSUIT_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06SPADES\x10\x01\x12\n" +
	"\n" +
	"\x06HEARTS\x10\x02\x12\t\n" +
	"\x05CLUBS\x10\x03\x12\f\n" +
	"\bDIAMONDS\x10\x04*\x9a\x01\n" +
	"\x04Rank\x12\x10\n" +
	"\fRANK_UNKNOWN\x10\x00\x12\a\n" +
	"\x03ACE\x10\x01\x12\a\n" +
	"\x03TWO\x10\x02\x12\t\n" +
	"\x05THREE\x10\x03\x12\b\n" +
	"\x04FOUR\x10\x04\x12\b\n" +
	"\x04FIVE\x10\x05\x12\a\n" +
	"\x03SIX\x10\x06\x12\t\n" +
	"\x05SEVEN\x10\a\x12\t\n" +
	"\x05EIGHT\x10\b\x12\b\n" +
	"\x04NINE\x10\t\x12\a\n" +
	"\x03TEN\x10\n" +
	"\x12\b\n" +
	"\x04JACK\x10\v\x12\t\n" +
	"\x05QUEEN\x10\f\x12\b\n" +
	"\x04KING\x10\r*\xd5\x01\n" +
	"\vCardPattern\x12\x13\n" +
	"\x0fPATTERN_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06NO_NIU\x10\x01\x12\t\n" +
	"\x05NIU_1\x10\x02\x12\t\n" +
	"\x05NIU_2\x10\x03\x12\t\n" +
	"\x05NIU_3\x10\x04\x12\t\n" +
	"\x05NIU_4\x10\x05\x12\t\n" +
	"\x05NIU_5\x10\x06\x12\t\n" +
	"\x05NIU_6\x10\a\x12\t\n" +
	"\x05NIU_7\x10\b\x12\t\n" +
	"\x05NIU_8\x10\t\x12\t\n" +
	"\x05NIU_9\x10\n" +
	"\x12\v\n" +
	"\aNIU_NIU\x10\v\x12\x13\n" +
	"\x0fFIVE_FLOWER_NIU\x10\f\x12\f\n" +
	"\bBOMB_NIU\x10\r\x12\x12\n" +
	"\x0eFIVE_SMALL_NIU\x10\x0e*G\n" +
	"\fPlayerStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\v\n" +
	"\aWAITING\x10\x01\x12\t\n" +
	"\x05READY\x10\x02\x12\v\n" +
	"\aPLAYING\x10\x03*|\n" +
	"\tGameState\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13WAITING_FOR_PLAYERS\x10\x01\x12\v\n" +
	"\aDEALING\x10\x02\x12\v\n" +
	"\aBIDDING\x10\x03\x12\v\n" +
	"\aBETTING\x10\x04\x12\f\n" +
	"\bSHOWDOWN\x10\x05\x12\x0e\n" +
	"\n" +
	"SETTLEMENT\x10\x06B\x1aZ\x18xizexcample/internal/msgb\x06proto3"

var (
	file_api_proto_game_proto_rawDescOnce sync.Once
	file_api_proto_game_proto_rawDescData []byte
)

func file_api_proto_game_proto_rawDescGZIP() []byte {
	file_api_proto_game_proto_rawDescOnce.Do(func() {
		file_api_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_game_proto_rawDesc), len(file_api_proto_game_proto_rawDesc)))
	})
	return file_api_proto_game_proto_rawDescData
}

var file_api_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_api_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_game_proto_goTypes = []any{
	(MsgID)(0),                   // 0: game.MsgID
	(Suit)(0),                    // 1: game.Suit
	(Rank)(0),                    // 2: game.Rank
	(CardPattern)(0),             // 3: game.CardPattern
	(PlayerStatus)(0),            // 4: game.PlayerStatus
	(GameState)(0),               // 5: game.GameState
	(*Card)(nil),                 // 6: game.Card
	(*PlayerInfo)(nil),           // 7: game.PlayerInfo
	(*C2S_JoinRoomReq)(nil),      // 8: game.C2S_JoinRoomReq
	(*C2S_PlayerReadyReq)(nil),   // 9: game.C2S_PlayerReadyReq
	(*C2S_BidBankerReq)(nil),     // 10: game.C2S_BidBankerReq
	(*C2S_PlaceBetReq)(nil),      // 11: game.C2S_PlaceBetReq
	(*C2S_ShowdownReq)(nil),      // 12: game.C2S_ShowdownReq
	(*C2S_LeaveRoomReq)(nil),     // 13: game.C2S_LeaveRoomReq
	(*S2C_JoinRoomAck)(nil),      // 14: game.S2C_JoinRoomAck
	(*S2C_BidBankerAck)(nil),     // 15: game.S2C_BidBankerAck
	(*S2C_PlaceBetAck)(nil),      // 16: game.S2C_PlaceBetAck
	(*S2C_ShowdownAck)(nil),      // 17: game.S2C_ShowdownAck
	(*RoomInfo)(nil),             // 18: game.RoomInfo
	(*S2C_SyncRoomStateNtf)(nil), // 19: game.S2C_SyncRoomStateNtf
	(*S2C_GameStartNtf)(nil),     // 20: game.S2C_GameStartNtf
	(*S2C_DealCardsNtf)(nil),     // 21: game.S2C_DealCardsNtf
	(*S2C_BidBankerNtf)(nil),     // 22: game.S2C_BidBankerNtf
	(*S2C_BetNtf)(nil),           // 23: game.S2C_BetNtf
	(*S2C_ShowdownNtf)(nil),      // 24: game.S2C_ShowdownNtf
	(*PlayerResult)(nil),         // 25: game.PlayerResult
	(*S2C_GameResultNtf)(nil),    // 26: game.S2C_GameResultNtf
	(*S2C_PlayerLeaveNtf)(nil),   // 27: game.S2C_PlayerLeaveNtf
}
var file_api_proto_game_proto_depIdxs = []int32{
	1,  // 0: game.Card.suit:type_name -> game.Suit
	2,  // 1: game.Card.rank:type_name -> game.Rank
	4,  // 2: game.PlayerInfo.status:type_name -> game.PlayerStatus
	6,  // 3: game.PlayerInfo.hand:type_name -> game.Card
	3,  // 4: game.PlayerInfo.card_pattern:type_name -> game.CardPattern
	6,  // 5: game.C2S_ShowdownReq.sorted_hand:type_name -> game.Card
	18, // 6: game.S2C_JoinRoomAck.room_info:type_name -> game.RoomInfo
	7,  // 7: game.RoomInfo.players:type_name -> game.PlayerInfo
	5,  // 8: game.RoomInfo.game_state:type_name -> game.GameState
	18, // 9: game.S2C_SyncRoomStateNtf.room_info:type_name -> game.RoomInfo
	6,  // 10: game.S2C_DealCardsNtf.hand:type_name -> game.Card
	6,  // 11: game.PlayerResult.hand:type_name -> game.Card
	3,  // 12: game.PlayerResult.card_pattern:type_name -> game.CardPattern
	25, // 13: game.S2C_GameResultNtf.results:type_name -> game.PlayerResult
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_game_proto_init() }
func file_api_proto_game_proto_init() {
	if File_api_proto_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_game_proto_rawDesc), len(file_api_proto_game_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_game_proto_goTypes,
		DependencyIndexes: file_api_proto_game_proto_depIdxs,
		EnumInfos:         file_api_proto_game_proto_enumTypes,
		MessageInfos:      file_api_proto_game_proto_msgTypes,
	}.Build()
	File_api_proto_game_proto = out.File
	file_api_proto_game_proto_goTypes = nil
	file_api_proto_game_proto_depIdxs = nil
}
